# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./Seguridad/Autorizacion.Middleware
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./Seguridad/Autorizacion.Middleware
    - name: Pack      
      run: dotnet pack
      working-directory: ./Seguridad/Autorizacion.Middleware

    - uses: actions/upload-artifact@v3
      with:
        name: Autorizacion.Middleware.1.0.0
        if-no-files-found: error
        retention-days: 7
        path: /home/runner/work/PaqueteProyecto/Seguridad/Autorizacion.Middleware/*/*/*/*.nupkg
              #Seguridad/Autorizacion.Middleware/Autorizacion.Middleware.csproj
  release:
    runs-on: ubuntu-latest    
    needs: build
    steps:  
    - name: Checkout 
      uses: actions/checkout@v3

    - name: Downlod Artifacts 
      uses: actions/download-artifact@v3

    - name: List Files
      run: ls -R

    - name: Prep packages
      run: dotnet nuget add source --username RODRIGUEZBARBOZAVALERIA --password ${{ secrets.PAQUETEP_TOKEN }} --store-password-in-clear-text --name paquetes "https://nuget.pkg.github.com/RODRIGUEZBARBOZAVALERIA/index.json"
    - name: Push package to GitHub packages 
      run: dotnet nuget push ./Seguridad/Autorizacion.Middleware/*/*/*/*.nupkg --api-key ${{ secrets.PAQUETEP_TOKEN }}  --source "paquetes" --skip-duplicate
